//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EXAM
{
    using System;
    using System.Collections.Generic;
    
    public partial class başvuru
    {
        public int Başvuru_İD { get; set; }
        public string AD { get; set; }
        public string SOYAD { get; set; }
        public string ceb_telefon { get; set; }
        public string Email { get; set; }
        public Nullable<System.DateTime> Dogum_Tarihi { get; set; }
        public string Cinsiyet { get; set; }
        public string Uyruk { get; set; }
        public string calisma { get; set; }
        public string Engelli_Durumu { get; set; }
        public string Egitim_Durumu { get; set; }
        public string Egitim_seviye { get; set; }
        public string ToplamYıl { get; set; }
        public string herhangi_yerde_calismak { get; set; }
        public string İs_tecrube_girmek { get; set; }
        public string pozisyon { get; set; }
    }
}
